/*
 * Lukas Krampitz
 * Mar 25 2021
 * Allow the user to select settings that are constant across all games.
 */
package krampitzkreutzwisersettlersofcatan;

import textures.ImageRef;

/**
 *
 * @author Tacitor
 * @author Evan
 */
public class ClientSettings extends javax.swing.JFrame {

    private final MainMenu mainMenuFrame;

    /**
     * Creates new form CreditsUI
     *
     * @param m The main menu JFrame this returns to on exit
     * @param g
     */
    public ClientSettings(MainMenu m) {
        setIcon();

        initComponents();
        mainMenuFrame = m;
    }

    /**
     * Set the icon for the JFRame
     */
    private void setIcon() {
        this.setIconImage(ImageRef.ICON);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playerNumGrp = new javax.swing.ButtonGroup();
        onlineModeGrp = new javax.swing.ButtonGroup();
        startResGrp = new javax.swing.ButtonGroup();
        snakeRulesGrp = new javax.swing.ButtonGroup();
        backBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        titleLbl = new javax.swing.JLabel();
        boarderLbl = new javax.swing.JLabel();
        boarderFalseRbtn = new javax.swing.JRadioButton();
        boarderTrueRbtn = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        backBtn.setText("< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        saveBtn.setFont(new java.awt.Font("MV Boli", 0, 16)); // NOI18N
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        titleLbl.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLbl.setText("Game Client Settings");

        boarderLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        boarderLbl.setText("Show Menu boarders");

        onlineModeGrp.add(boarderFalseRbtn);
        boarderFalseRbtn.setSelected(true);
        boarderFalseRbtn.setText("No");
        boarderFalseRbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boarderFalseRbtnActionPerformed(evt);
            }
        });

        onlineModeGrp.add(boarderTrueRbtn);
        boarderTrueRbtn.setText("Yes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boarderLbl)
                            .addComponent(boarderFalseRbtn)
                            .addComponent(boarderTrueRbtn)
                            .addComponent(backBtn))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(titleLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(boarderLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boarderFalseRbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(boarderTrueRbtn)
                .addGap(41, 41, 41)
                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * The event for when the back button is pressed. Returns to the main menu.
     *
     * @param evt The event generated by the button click (Unused)
     */
    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // Hide this window and show the main menu
        this.setVisible(false);
        mainMenuFrame.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        //get the online play mode

        //get and set the giveStartingResources
        if (boarderTrueRbtn.isSelected()) {
            GamePanel.setShowMenuBoarder(true);
        } else if (boarderFalseRbtn.isSelected()) {
            GamePanel.setShowMenuBoarder(false);
        }

    }//GEN-LAST:event_saveBtnActionPerformed

    private void boarderFalseRbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boarderFalseRbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boarderFalseRbtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JRadioButton boarderFalseRbtn;
    private javax.swing.JLabel boarderLbl;
    private javax.swing.JRadioButton boarderTrueRbtn;
    private javax.swing.ButtonGroup onlineModeGrp;
    private javax.swing.ButtonGroup playerNumGrp;
    private javax.swing.JButton saveBtn;
    private javax.swing.ButtonGroup snakeRulesGrp;
    private javax.swing.ButtonGroup startResGrp;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
